CREATE TABLE IF NOT EXISTS USERS_ENTITY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255),
  password VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS CLIENT_ENTITY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  email VARCHAR(255),
  identification VARCHAR(255),
  agency VARCHAR(255),
  IS_ACTIVE BOOLEAN
);